# change name
name: Build and Unit test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    # change name
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            # Add name
            - name: Checkout the code
              # change versions
              uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  # change name
                  node-version: 20.x
                  cache: "npm"
            # change name
            - name: Install npm dependencies
              run: npm install
            # Add name
            - name: Execute the  unit tests
              run: npm run test:unit
